/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package br.com.projeto_livraria.view;

import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import br.com.projeto_livraria.dto.FuncionarioDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author guiva
 */
public class PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVIEW
     */
    public PrincipalVIEW(FuncionarioDTO funcionarioDTO) {
        initComponents();
        this.setLocationRelativeTo(null);
        if(funcionarioDTO.getTipo_fun().equalsIgnoreCase("COMUM")){
            ItemMenuCadastro.setVisible( false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageicon = new ImageIcon(getClass().getResource("imagens/biblioteca.png"));
        Image image = imageicon.getImage();

        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics graphics){
                graphics.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        }

        ;
        menuBar = new javax.swing.JMenuBar();
        ItemMenuCadastro = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        itemEditora = new javax.swing.JMenuItem();
        itemLivro = new javax.swing.JMenuItem();
        itemMenuFuncionario = new javax.swing.JMenuItem();
        pedido = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1388, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        ItemMenuCadastro.setMnemonic('f');
        ItemMenuCadastro.setText("Cadastrar");
        ItemMenuCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemMenuCadastroMouseClicked(evt);
            }
        });
        ItemMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemMenuCadastroActionPerformed(evt);
            }
        });

        itemCliente.setMnemonic('o');
        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        ItemMenuCadastro.add(itemCliente);

        itemEditora.setMnemonic('s');
        itemEditora.setText("Editora");
        itemEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditoraActionPerformed(evt);
            }
        });
        ItemMenuCadastro.add(itemEditora);

        itemLivro.setMnemonic('a');
        itemLivro.setText("Livro");
        itemLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLivroActionPerformed(evt);
            }
        });
        ItemMenuCadastro.add(itemLivro);

        itemMenuFuncionario.setText("Funcionário");
        itemMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncionarioActionPerformed(evt);
            }
        });
        ItemMenuCadastro.add(itemMenuFuncionario);

        menuBar.add(ItemMenuCadastro);

        pedido.setMnemonic('e');
        pedido.setText("Pedido");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Realizar Pedido");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        pedido.add(cutMenuItem);

        menuBar.add(pedido);

        sair.setMnemonic('h');
        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        menuBar.add(sair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        sair();
    }//GEN-LAST:event_sairMouseClicked

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        abreClienteVIEW();
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditoraActionPerformed
        abreEditoraVIEW();
    }//GEN-LAST:event_itemEditoraActionPerformed

    private void itemLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLivroActionPerformed
        abreLivroVIEW();
    }//GEN-LAST:event_itemLivroActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        abrePedidoVIEW();
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void ItemMenuCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemMenuCadastroMouseClicked
       
    }//GEN-LAST:event_ItemMenuCadastroMouseClicked

    private void ItemMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemMenuCadastroActionPerformed
       abreFuncionarioVIEW();
    }//GEN-LAST:event_ItemMenuCadastroActionPerformed

    private void itemMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncionarioActionPerformed
        abreFuncionarioVIEW();
    }//GEN-LAST:event_itemMenuFuncionarioActionPerformed
    
    private void sair() {
        Object[] options = {"Sair", "Cancelar"};
        if (JOptionPane.showOptionDialog(null, "Deseja Sair do Sistema", "Informação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0) {
            System.exit(0);
        }
    }

    private void abreClienteVIEW() {
        ClienteVIEW clienteVIEW = new ClienteVIEW();
        this.desktopPane.add(clienteVIEW);
        clienteVIEW.setVisible(true);
        clienteVIEW.setPosicao();
    }

    private void abreLivroVIEW() {
        LivroVIEW livroVIEW = new LivroVIEW();
        this.desktopPane.add(livroVIEW);
        livroVIEW.setVisible(true);
        livroVIEW.setPosicao();
    }

    private void abreEditoraVIEW() {
        EditoraVIEW editoraVIEW = new EditoraVIEW();
        this.desktopPane.add(editoraVIEW);
        editoraVIEW.setVisible(true);
        editoraVIEW.setPosicao();
    }

    private void abrePedidoVIEW() {
        PedidoVIEW pedidoVIEW = new PedidoVIEW();
        this.desktopPane.add(pedidoVIEW);
        pedidoVIEW.setVisible(true);
        pedidoVIEW.setPosicao();
    }

    private void abreFuncionarioVIEW() {
        FuncionarioVIEW funcionarioVIEW = new FuncionarioVIEW();
        this.desktopPane.add(funcionarioVIEW);
        funcionarioVIEW.setVisible(true);
        funcionarioVIEW.setPosicao();
    }

    
    
    /**
     * @param args the command line arguments
     */
 //   public static void main(String args[]) {
         //Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         // For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
///        try {
   ///         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
      //          if ("Nimbus".equals(info.getName())) {
        //            javax.swing.UIManager.setLookAndFeel(info.getClassName());
          //          break;
            //    }
            //}
        //} catch (ClassNotFoundException ex) {
         //   java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
          //  java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
          //  java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (javax.swing.UnsupportedLookAndFeelException ex) {
          //  java.util.logging.Logger.getLogger(PrincipalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

       /*Create and display the form */
      // java.awt.EventQueue.invokeLater(new Runnable() {
          //  public void run() {
         //       new PrincipalVIEW().setVisible(true)
       //     }
      //  });
   // }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ItemMenuCadastro;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemEditora;
    private javax.swing.JMenuItem itemLivro;
    private javax.swing.JMenuItem itemMenuFuncionario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu pedido;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables

}
